FROM ubuntu

USER root

# Install Python 3.11 and pip
RUN apt-get update && apt-get install -y python3.11 python3-pip
RUN ln -s /usr/bin/python3 /usr/bin/python

# Update alternatives to use Python 3.11
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

# Install Java 17 Amazon Corretto
RUN apt-get install -y wget gnupg && \
    wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz && \
    tar -xzf amazon-corretto-17-x64-linux-jdk.tar.gz -C /usr/local && \
    rm amazon-corretto-17-x64-linux-jdk.tar.gz && \
    mv /usr/local/amazon-corretto-17.0.9.8.1-linux-x64 /usr/local/amazon-corretto-17
ENV JAVA_HOME=/usr/local/amazon-corretto-17
ENV PATH=$PATH:$JAVA_HOME/bin

# Install miniconda
RUN mkdir -p ~/miniconda3
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
RUN bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
RUN rm -rf ~/miniconda3/miniconda.sh
RUN ~/miniconda3/bin/conda init bash
RUN ~/miniconda3/bin/conda init zsh

# Set working directory
WORKDIR /app

# Copy jar
COPY /target/readability-decreasing-heuristics-1.0-SNAPSHOT-jar-with-dependencies.jar /app/rdh.jar

# Copy code2vec requirements
COPY /code2vec/requirements.txt /app

# Create a conda environment from the requirements file
RUN ~/miniconda3/bin/conda create -n code2vec --file /app/requirements.txt -y

# Copy code2vec
# COPY /code2vec/java14_model /app/code2vec/java14_model
COPY /code2vec/ /app/code2vec

# Give write permission to the user
RUN chmod -R 777 /app

# Set Python path
ENV PYTHONPATH /app:/app/src:/app/src/readability_preprocessing:$PYTHONPATH
