newline:
  - 0.0  # Probability for no newline
  - 1.0  # Probability for one newline
incTab:
  - 0.0  # Probability for no tab
  - 1.0  # Probability for one tab
decTab:
  - 0.0  # Probability for no tab
  - 1.0  # Probability for one tab
space:
  - 0.0  # Probability for no space
  - 1.0  # Probability for one space
newLineInsteadOfSpace: 0
spaceInsteadOfNewline: 0
incTabInsteadOfDecTab: 0
decTabInsteadOfIncTab: 0
renameVariable: 1
renameField: 1
renameMethod: 1
inlineMethod: 0
removeComment: 0
add0: 0
insertBraces: 0
starImport: 0
inlineField: 0