condaPath: C:/Users/lukas/anaconda3/envs/code2vec
modelPath: C:/Users/lukas/PycharmProjects/Code2Vec/models/java14_model/saved_model_iter8.release
pythonScriptPath: C:/Users/lukas/PycharmProjects/code2vec
scope: FILE
renameMethodMode: ITERATIVE
outputMode: STRUCTURE_KEEPING