newline:
  - 0.0  # Probability for no newline
  - 1.0  # Probability for one newline
  - 0.0  # Probability for two newlines
  - 0.0  # Probability for three newlines
doubleTab: 0
noTab: 0
doubleSpace: 0
noSpace: 0
newLineInsteadOfSpace: 0
spaceInsteadOfNewline: 0