condaPath: / #[PATH_TO_ANACONDA]/envs/[CODE2VEC_ENV]
modelPath: / #[PATH_TO_CODE2VEC_MODEL].release
pythonScriptPath: / #[PATH_TO_CODE2VEC_PROJECT]
scope: FILE
renameMethodMode: REALISTIC
outputMode: NEW_DIRECTORY